### ISSUE TITLE
Build version differs from sources. 

### ISSUE THREAD

**Issue by reneviering** [moimikey/iso3166-1#23]
Hey,

First of all, thanks for your great library.  I've seen that the browserified build (iso3166-1.global.js) differs from the version in src/. 

The file »src/iso3166-1/index.j2« includes the following function, which i miss inside the build. 

``` javascript
var is3 = function is3(alpha3) {
    return ISOCodes.some(function(row) {
      return row.alpha3 === alpha3
    })
  }
```

Is it possible to rebuild the project and commit the build files?
That would be great!

I could also create a PR for that!?

Thanks!
René

**Comment by moimikey** [comment]
hey @revrng! thanks for taking the time to try it out! if you'd like to create the PR for some open source credit, you're more than welcome to fork the repo and do so! let me know, otherwise I don't mind rebuilding :)
