### ISSUE TITLE
buffer breaks in IE11

### ISSUE THREAD

**Issue by pcaleja** [moimikey/iso3166-1#43]
@moimikey 

Hola! I'm not sure if this is something that can be fixed in this module, but IE11 seems to have some some issues with `fromString` method of `buffer. Trying to look for a fix and I'll open a PR if I find one but maybe you have some ideas as well?

![screen shot 2016-04-18 at 3 56 41 pm](https://cloud.githubusercontent.com/assets/3833667/14652907/80626b48-0644-11e6-8559-a0db3c73e8dc.png)

**Comment by michael-hertzberg-zocdoc** [comment]
@pcaleja hi phillip :) taking a look now.

**Comment by pcaleja** [comment]
@michael-hertzberg-zocdoc 

Thanks! :)

**Comment by moimikey** [comment]
@pcaleja could you try pulling down version v0.2.6 and see if that fixes the problem?

**Comment by pcaleja** [comment]
@michael-hertzberg-zocdoc getting this error when I build, could be cause of my build task though.

```
Error: Cannot find module './zlib' from '/Users/philip/Documents/Websites/sk-marketing/node_modules/iso3166-1/lib'
```

**Comment by moimikey** [comment]
@pcaleja eep! pull 0.2.7 :)...

**Comment by pcaleja** [comment]
@michael-hertzberg-zocdoc 

It still persists. I noticed buffer updated this function. Not sure if it will help though. 

``` JS
function fromString(string, encoding) {
  if (typeof encoding !== 'string' || encoding === '')
    encoding = 'utf8';

  if (!Buffer.isEncoding(encoding))
    throw new TypeError('"encoding" must be a valid string encoding');

  var length = byteLength(string, encoding);

  if (length === 0)
    return Buffer.alloc(0);

  if (length >= (Buffer.poolSize >>> 1))
    return binding.createFromString(string, encoding);

  if (length > (poolSize - poolOffset))
    createPool();
  var actual = allocPool.write(string, poolOffset, encoding);
  var b = allocPool.slice(poolOffset, poolOffset + actual);
  poolOffset += actual;
  alignPool();
  return b;
}
```

Also it seems like `zlib-browserify` is now being searched outside of the module's node_module directory.

`Error: Cannot find module 'zlib-browserify' from '/Users/philip/Documents/Websites/sk-marketing/node_modules/iso3166-1/src'`

**Comment by moimikey** [comment]
@pcaleja lets try again >.< -- v0.2.8

after that, then i'll need to get back to you :(...

**Comment by pcaleja** [comment]
@moimikey 

Still persists :(.. It's not urgent since, I'll disable this for now in IE but it would be great to have a fix. Let me know if it's something on my side as well. Thanks again!

**Comment by moimikey** [comment]
i still want to revisit this... ie11 hell.

**Comment by pcaleja** [comment]
@moimikey last time I looked at it, the issue seems to be coming from `buffer` and I think node's newer version should fix these issues but I'm not 100% sure.

**Comment by moimikey** [comment]
fixed in latest version
