### ISSUE TITLE
event-stream versions with malware

### ISSUE THREAD

**Issue by aiankile** [moimikey/iso3166-1#72]
See https://github.com/dominictarr/event-stream/issues/115
Versions of event-stream above 3.3.4 contain malcious code.
In your package's lock file the version is set to 3.3.4 which is not affected -> current dist is fine.
However, please also restrict version in package.json to exactly 3.3.4 too.

**Comment by moimikey** [comment]
Got it, thank you.   
  
  
  

  
  

  
  
>
